### ISSUE TITLE
Issue with <docker run -it -v $PWD:/nodejsAction openwhisk/action-nodejs-v8 /bin/bash>

### ISSUE THREAD

**Issue by kareem-adel-1990** [IBM/ibm-cloud-functions-serverless-blockchain#13]
PS E:\04 Development Stage\ibm-cloud-functions-serverless-blockchain-master\cloud-functions\store-credentials-cloudant> 
>> docker run -it -v $PWD:/nodejsAction openwhisk/action-nodejs-v8 /bin/bash
At line:2 char:19
+ docker run -it -v $PWD:/nodejsAction openwhisk/action-nodejs-v8 /bin/ ...
Variable reference is not valid. ':' was not followed by a valid variable name character. Consider using ${} to delimit the name.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidVariableReferenceWithDrive

**Comment by ccorley** [comment]
Hi @kareem-adel-1990.  Can you please try using ${PWD} in the same command?
https://stackoverflow.com/questions/60789312/docker-docker-is-complaining-when-using-pwd-in-windows-10-pro

**Comment by ccorley** [comment]
Resolved.
