### ISSUE TITLE
Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v64-linux-x64-glibc\nFound: [node-v64-win32-x64-unknown]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module '/nodejsAction/PWQdbmc5/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'\n

### ISSUE THREAD

**Issue by kareem-adel-1990** [IBM/ibm-cloud-functions-serverless-blockchain#15]
hi corley, i invoked the store-credentials-cloudant successfully but when i invoked the Send-to-blockchain action i got these message
"Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v64-linux-x64-glibc\nFound: [node-v64-win32-x64-unknown]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module '/nodejsAction/PWQdbmc5/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'\n"
i tried to use npm rebuild and still the created file is node-v64-win32-x64-unknown not the required one node-v64-linux-x64-glibc
how can i fix this issue

**Comment by kareem-adel-1990** [comment]
Many thanks 
I solved the issue

**Comment by ccorley** [comment]
Great! What was the final resolution on this, in case it helps someone else?

**Comment by kareem-adel-1990** [comment]
npm rebuild --target=10.21.0 --target_platform=linux --target_arch=x64 --target_libc=glibc
